// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF6iPnA6F4908t9u2GKdd5SnQH0SesBg0',
    appId: '1:538238583501:web:72b78fdec7ccd37faa5f84',
    messagingSenderId: '538238583501',
    projectId: 'iotproject1-85bb8',
    authDomain: 'iotproject1-85bb8.firebaseapp.com',
    databaseURL: 'https://iotproject1-85bb8-default-rtdb.firebaseio.com',
    storageBucket: 'iotproject1-85bb8.firebasestorage.app',
    measurementId: 'G-C3QB4H3LGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVZFgaGMXfeNYW3NJjx9wWBknybAnOwyA',
    appId: '1:538238583501:android:a5b156b2af2e68aaaa5f84',
    messagingSenderId: '538238583501',
    projectId: 'iotproject1-85bb8',
    databaseURL: 'https://iotproject1-85bb8-default-rtdb.firebaseio.com',
    storageBucket: 'iotproject1-85bb8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF6iPnA6F4908t9u2GKdd5SnQH0SesBg0',
    appId: '1:538238583501:web:66840a9ce06a4f47aa5f84',
    messagingSenderId: '538238583501',
    projectId: 'iotproject1-85bb8',
    authDomain: 'iotproject1-85bb8.firebaseapp.com',
    databaseURL: 'https://iotproject1-85bb8-default-rtdb.firebaseio.com',
    storageBucket: 'iotproject1-85bb8.firebasestorage.app',
    measurementId: 'G-DQG5Y64D1T',
  );
}
